### ISSUE TITLE
Dialect needs to be explicitly supplied as of v4.0.0

### ISSUE THREAD

**Issue by Maushundb** [Alex-ray/v2-universal-js-hmr-ssr-react-redux#3]
Hey @Alex-ray, I'm trying to build this for development, and there appears to be an issue with Sequelize, namely that it no longer allows a config without an explicit dialect value in your database object. Any guidance here on how to get it running?

```
npm run development                                                                                                                                                                      master 236d4f4 ✗

> instawatch@1.0.0 development /Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux
> NODE_PATH=./src NODE_ENV=development node ./src/server/server.babel.js

/Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux/node_modules/sequelize/lib/sequelize.js:169
      throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^

Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux/node_modules/sequelize/lib/sequelize.js:169:13)
    at Object.<anonymous> (/Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux/src/database/sequelize.js:2:19)
    at Module._compile (module.js:569:30)
    at loader (/Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux/src/server/session.js:3:1)
    at Module._compile (module.js:569:30)
    at loader (/Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux/src/server/server.js:10:1)
    at Module._compile (module.js:569:30)
    at loader (/Users/maushundb/Dropbox (Personal)/Samble/Code/v2-universal-js-hmr-ssr-react-redux/node_modules/babel-register/lib/node.js:144:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! instawatch@1.0.0 development: `NODE_PATH=./src NODE_ENV=development node ./src/server/server.babel.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the instawatch@1.0.0 development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maushundb/.npm/_logs/2017-07-02T23_50_12_287Z-debug.log
```

**Comment by Alex-ray** [comment]
Hey @Maushundb , so sorry about this! I am actually building a side project using Sequelize and docker. I must have accidentally pushed it up to this repository by accident....  😱 

Things should be back to normal now! 

Definitley let me know if you have any other troubles 🙂
